
# Get Jekyll from https://hub.docker.com/r/jekyll/jekyll/
FROM jekyll/jekyll 

# Copy all files from local project to container jekyll working directory.
COPY ./ /srv/jekyll/

# Run jekyll build.  
RUN jekyll build

# Set a working directory and copy the output files there:
# WORKDIR /output
# COPY /srv/jekyll/_site /output/

# Get the nginx webserver image
FROM nginx

# Copy the output from container jekyll build to nginx web server 

COPY /srv/jekyll/_site /usr/share/nginx/html
